export const classicLogic = [
	{ letter: ' ', number: 0 },
	{ letter: 'a', number: 1 },
	{ letter: 'b', number: 2 },
	{ letter: 'c', number: 3 },
	{ letter: 'd', number: 4 },
	{ letter: 'e', number: 5 },
	{ letter: 'f', number: 6 },
	{ letter: 'g', number: 7 },
	{ letter: 'h', number: 8 },
	{ letter: 'i', number: 9 },
	{ letter: 'j', number: 10 },
	{ letter: 'k', number: 11 },
	{ letter: 'l', number: 12 },
	{ letter: 'm', number: 13 },
	{ letter: 'n', number: 14 },
	{ letter: 'o', number: 15 },
	{ letter: 'p', number: 16 },
	{ letter: 'q', number: 17 },
	{ letter: 'r', number: 18 },
	{ letter: 's', number: 19 },
	{ letter: 't', number: 20 },
	{ letter: 'u', number: 21 },
	{ letter: 'v', number: 22 },
	{ letter: 'w', number: 23 },
	{ letter: 'x', number: 24 },
	{ letter: 'y', number: 25 },
	{ letter: 'z', number: 26 },
];

export const inverseLogic = [
	{ letter: ' ', number: 0 },
	{ letter: 'z', number: 1 },
	{ letter: 'y', number: 2 },
	{ letter: 'x', number: 3 },
	{ letter: 'w', number: 4 },
	{ letter: 'v', number: 5 },
	{ letter: 'u', number: 6 },
	{ letter: 't', number: 7 },
	{ letter: 's', number: 8 },
	{ letter: 'r', number: 9 },
	{ letter: 'q', number: 10 },
	{ letter: 'p', number: 11 },
	{ letter: 'o', number: 12 },
	{ letter: 'n', number: 13 },
	{ letter: 'm', number: 14 },
	{ letter: 'l', number: 15 },
	{ letter: 'k', number: 16 },
	{ letter: 'j', number: 17 },
	{ letter: 'i', number: 18 },
	{ letter: 'h', number: 19 },
	{ letter: 'g', number: 20 },
	{ letter: 'f', number: 21 },
	{ letter: 'e', number: 22 },
	{ letter: 'd', number: 23 },
	{ letter: 'c', number: 24 },
	{ letter: 'b', number: 25 },
	{ letter: 'a', number: 26 },
];

export const allDigits = [
	{ letter: '0', frenchNumber: 'zero' },
	{ letter: '1', frenchNumber: 'un' },
	{ letter: '2', frenchNumber: 'deux' },
	{ letter: '3', frenchNumber: 'trois ' },
	{ letter: '4', frenchNumber: 'quatre ' },
	{ letter: '5', frenchNumber: 'cinq' },
	{ letter: '6', frenchNumber: 'six' },
	{ letter: '7', frenchNumber: 'sept' },
	{ letter: '8', frenchNumber: 'huit' },
	{ letter: '9', frenchNumber: 'neuf' },
	{ letter: '10', frenchNumber: 'dix' },
	{ letter: '11', frenchNumber: 'onze' },
	{ letter: '12', frenchNumber: 'douze' },
	{ letter: '13', frenchNumber: 'treize' },
	{ letter: '14', frenchNumber: 'quatorze' },
	{ letter: '15', frenchNumber: 'quinze' },
	{ letter: '16', frenchNumber: 'seize' },
	{ letter: '17', frenchNumber: 'dix sept' },
	{ letter: '18', frenchNumber: 'dix huit' },
	{ letter: '19', frenchNumber: 'dix neuf' },
	{ letter: '20', frenchNumber: 'vingt ' },
	{ letter: '21', frenchNumber: 'vingt et un' },
	{ letter: '22', frenchNumber: 'vingt deux' },
	{ letter: '23', frenchNumber: 'vingt trois' },
	{ letter: '24', frenchNumber: 'vingt quatre' },
	{ letter: '25', frenchNumber: 'vingt cinq' },
	{ letter: '26', frenchNumber: 'vingt six' },
	{ letter: '27', frenchNumber: 'vingt sept' },
	{ letter: '28', frenchNumber: 'vingt huit' },
	{ letter: '29', frenchNumber: 'vingt neuf' },
	{ letter: '30', frenchNumber: 'trente' },
	{ letter: '31', frenchNumber: 'trente et un' },
	{ letter: '32', frenchNumber: 'trente deux' },
	{ letter: '33', frenchNumber: 'trente trois' },
	{ letter: '34', frenchNumber: 'trente quatre' },
	{ letter: '35', frenchNumber: 'trente cinq' },
	{ letter: '36', frenchNumber: 'trente six' },
	{ letter: '37', frenchNumber: 'trente sept' },
	{ letter: '38', frenchNumber: 'trente huit' },
	{ letter: '39', frenchNumber: 'trente neuf' },
	{ letter: '40', frenchNumber: 'quarante' },
	{ letter: '41', frenchNumber: 'quarante et un' },
	{ letter: '42', frenchNumber: 'quarante deux' },
	{ letter: '43', frenchNumber: 'quarante trois' },
	{ letter: '44', frenchNumber: 'quarante quatre' },
	{ letter: '45', frenchNumber: 'quarante cinq' },
	{ letter: '46', frenchNumber: 'quarante six' },
	{ letter: '47', frenchNumber: 'quarante sept' },
	{ letter: '48', frenchNumber: 'quarante huit' },
	{ letter: '49', frenchNumber: 'quarante neuf' },
	{ letter: '50', frenchNumber: 'cinquante' },
	{ letter: '51', frenchNumber: 'cinquante et un' },
	{ letter: '52', frenchNumber: 'cinquante deux' },
	{ letter: '53', frenchNumber: 'cinquante trois' },
	{ letter: '54', frenchNumber: 'cinquante quatre' },
	{ letter: '55', frenchNumber: 'cinquante cinq' },
	{ letter: '56', frenchNumber: 'cinquante six' },
	{ letter: '57', frenchNumber: 'cinquante sept' },
	{ letter: '58', frenchNumber: 'cinquante huit' },
	{ letter: '59', frenchNumber: 'cinquante neuf' },
	{ letter: '60', frenchNumber: 'soixante' },
	{ letter: '61', frenchNumber: 'soixante et un' },
	{ letter: '62', frenchNumber: 'soixante deux' },
	{ letter: '63', frenchNumber: 'soixante trois' },
	{ letter: '64', frenchNumber: 'soixante quatre' },
	{ letter: '65', frenchNumber: 'soixante cinq' },
	{ letter: '66', frenchNumber: 'soixante six' },
	{ letter: '67', frenchNumber: 'soixante sept' },
	{ letter: '68', frenchNumber: 'soixante huit' },
	{ letter: '69', frenchNumber: 'soixante neuf' },
	{ letter: '70', frenchNumber: 'soixante dix' },
	{ letter: '71', frenchNumber: 'soixante et onze' },
	{ letter: '72', frenchNumber: 'soixante douze' },
	{ letter: '73', frenchNumber: 'soixante treize' },
	{ letter: '74', frenchNumber: 'soixante quatorze' },
	{ letter: '75', frenchNumber: 'soixante quinze' },
	{ letter: '76', frenchNumber: 'soixante seize' },
	{ letter: '77', frenchNumber: 'soixante dix sept' },
	{ letter: '78', frenchNumber: 'soixante dix huit' },
	{ letter: '79', frenchNumber: 'soixante dix neuf' },
	{ letter: '80', frenchNumber: 'quatre vingt' },
	{ letter: '81', frenchNumber: 'quatre vingt un' },
	{ letter: '82', frenchNumber: 'quatre vingt deux' },
	{ letter: '83', frenchNumber: 'quatre vingt trois' },
	{ letter: '84', frenchNumber: 'quatre vingt quatre' },
	{ letter: '85', frenchNumber: 'quatre vingt cinq' },
	{ letter: '86', frenchNumber: 'quatre vingt six' },
	{ letter: '87', frenchNumber: 'quatre vingt sept' },
	{ letter: '88', frenchNumber: 'quatre vingt huit' },
	{ letter: '89', frenchNumber: 'quatre vingt neuf' },
	{ letter: '90', frenchNumber: 'quatre vingt dix' },
	{ letter: '91', frenchNumber: 'quatre vingt onze' },
	{ letter: '92', frenchNumber: 'quatre vingt douze' },
	{ letter: '93', frenchNumber: 'quatre vingt treize' },
	{ letter: '94', frenchNumber: 'quatre vingt quatorze' },
	{ letter: '95', frenchNumber: 'quatre vingt quinze' },
	{ letter: '96', frenchNumber: 'quatre vingt seize' },
	{ letter: '97', frenchNumber: 'quatre vingt dix sept' },
	{ letter: '98', frenchNumber: 'quatre vingt dix huit' },
	{ letter: '99', frenchNumber: 'quatre vingt dix neuf' },
];
